version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
